Friend Module Names
    Friend ReadOnly ASS_KEY As String = "ass key"
    Friend ReadOnly BED As String = "bed"
    Friend ReadOnly CELLAR As String = "cellar"
    Friend ReadOnly CELLAR_KEY As String = "cellar key"
    Friend ReadOnly CRATE As String = "crate"
    Friend ReadOnly GORACHAN As String = "Gorachan"
    Friend ReadOnly JUSDATIP_INN As String = "Jusdatip Inn"
    Friend ReadOnly N00B As String = "N00b"
    Friend ReadOnly RAT As String = "rat"
    Friend ReadOnly RUSTY_DAGGER As String = "rusty dagger"
    Friend ReadOnly THE_BLUE_ROOM As String = "the blue room"
    Friend ReadOnly THE_LOFT As String = "the loft"
    Friend ReadOnly THE_NEXT_ROOM As String = "the next room"
    Friend ReadOnly YLIOPPILASLAKKI As String = "ylioppilaslakki"
    Friend ReadOnly RAT_TAIL As String = "rat tail"
    Friend ReadOnly HEALER_HOUSE As String = "Nihilistic House of Healing"
    Friend ReadOnly MÅRTEN As String = "Mårten"
End Module
